import requests
import json

# --- Configuration ---
POKEAPI_BASE_URL = "https://pokeapi.co/api/v2/"

# Set limit to 493 (Gen 1-4)
POKEMON_LIMIT = 493

# A prioritized list of version groups for Gen 4.
# We prioritize the most "complete" versions of that generation.
FALLBACK_VERSION_GROUPS = [
    "heartgold-soulsilver", # Gen 4 (Most complete for 1-493)
    "platinum",             # Gen 4
    "diamond-pearl",        # Gen 4
    "emerald",              # Gen 3 (as fallback)
    "firered-leafgreen",    # Gen 3 (as fallback)
    "ruby-sapphire"         # Gen 3 (as fallback)
]


def generate_pokemon_data():
    """
    Fetches data from PokéAPI for all Gen 1-4 Pokémon (up to 493)
    and saves it into a Python file.
    """
    print("--- Starting Pokémon Data Generation (Gen 1-4) ---")
    pokemon_database = {}

    response = requests.get(f"{POKEAPI_BASE_URL}pokemon?limit={POKEMON_LIMIT}")
    if response.status_code != 200:
        print("Failed to fetch Pokémon list.")
        return

    pokemon_list = response.json()['results']

    for i, p in enumerate(pokemon_list):
        pokemon_name = p['name']
        print(f"Fetching data for ({i+1}/{POKEMON_LIMIT}): {pokemon_name.capitalize()}...")

        try:
            detail_response = requests.get(p['url'])
            if detail_response.status_code != 200:
                print(f"  -> Failed to fetch details for {pokemon_name}. Skipping.")
                continue
            
            data = detail_response.json()

            # --- Stat and Type extraction ---
            stats = {stat['stat']['name']: stat['base_stat'] for stat in data['stats']}
            formatted_stats = {
                "hp": stats.get("hp", 0), "atk": stats.get("attack", 0),
                "def": stats.get("defense", 0), "spa": stats.get("special-attack", 0),
                "spd": stats.get("special-defense", 0), "spe": stats.get("speed", 0),
            }
            types = [t['type']['name'] for t in data['types']]
            
            # --- Ability Logic ---
            # Save the raw, lowercase, hyphenated ability name.
            # This is the format poke-battle-sim requires (e.g., "sand-veil").
            ability = next((a['ability']['name'] for a in data['abilities'] if not a['is_hidden']), "unknown")

            # --- Learnset Logic with Fallback ---
            learnset = set()
            found_generation = None

            for version_group in FALLBACK_VERSION_GROUPS:
                temp_learnset = set()
                for move_data in data['moves']:
                    for version_details in move_data['version_group_details']:
                        if version_details['version_group']['name'] == version_group:
                            # Add the correctly formatted, hyphenated move name
                            temp_learnset.add(move_data['move']['name'])
                            break # Go to the next move
                
                # If we found moves in this generation, we are done
                if temp_learnset:
                    learnset = temp_learnset
                    found_generation = version_group
                    print(f"  -> Success! Using learnset from '{found_generation}'.")
                    break # Exit the fallback loop
            
            if not learnset:
                print(f"  -> Warning: No moves found for {pokemon_name} in any target generations. Skipping moveset.")

            # --- Assemble the dictionary ---
            pokemon_database[pokemon_name] = {
                "base_stats": formatted_stats,
                "types": types,
                "ability": ability,
                "learnset": sorted(list(learnset))
            }

        except Exception as e:
            print(f"  -> An error occurred while processing {pokemon_name}: {e}")

    # --- Write data to file ---
    file_path = "pokemon_data.py"
    print(f"\n--- Writing data to {file_path} ---")
    try:
        with open(file_path, "w") as f:
            f.write("# pokemon_data.py\n\n")
            f.write("# This file was auto-generated by generate_data.py\n")
            f.write("# Contains data for Pokémon 1-493 (Gen 1-4)\n")
            f.write("POKEMON_DATABASE = ")
            f.write(json.dumps(pokemon_database, indent=4))
        print("--- Data generation complete! ---")
    except Exception as e:
        print(f"Failed to write to file: {e}")


if __name__ == "__main__":
    generate_pokemon_data()